### ISSUE TITLE
sass/postcss support in AOT

### ISSUE THREAD

**Issue by fxck** [katallaxie/angular2-preboot#48]
@katallaxie I read this https://github.com/AngularClass/angular2-webpack-starter/pull/1347#issuecomment-271074737 but sass is nevertheless still the most popular preprocessor out there, not to mention it's required to when you want to create your own material2 theme https://github.com/angular/material2/blob/master/guides/theming-your-components.md and/or use style your own components using material themes. 

The question is, how to support sass properly? I mean adding `sass-loader` for JIT is simple enough..

```typescript
      {
        test: /\.scss$/,
        use: [
          'to-string-loader',
          'css-loader',
          'sass-loader',
          'postcss-loader'
        ],
      }
```

..but the question is what `@ngtools/webpack` does with it once you try to compile your app with AOT, what if you have some specific sass settings(something like `includePaths` settings.. `@ngtools/webpack` handles sass internally, right? It doesn't take in account your webpack settings, so it would ignore any `sass-loader` settings)?

Also the same goes for `postcss-loader`, doesn't it? 

One thing that comes to mind is to do the whole sass, postcss chain separately, generate the result to the same folder as the source is and include the result in `@Component`, which is what https://github.com/qdouble/angular-webpack2-starter does.. but it's kinda ugly.

**Comment by fxck** [comment]
Just tested it, 

```typescript
    new LoaderOptionsPlugin({
      debug: true,
      options: {
        sassLoader: {
          includePaths: [ root('src/app/styles') ]
        }
      }
    }),
```

works fine in jit, throws in aot, but strangely enough autoprefixer seems to be working fine in aot, so maybe I'm just doing something wrong.

**Comment by katallaxie** [comment]
Have a look at one my use cases.

```import { LoaderOptionsPlugin } from 'webpack';
import { root } from './helpers.ts';
import * as Autoprefixer from 'autoprefixer';
import * as CssNano from 'cssnano';
import * as ScriptExtHtmlWebpackPlugin from 'script-ext-html-webpack-plugin';
import * as ExtractTextWebpackPlugin from 'extract-text-webpack-plugin';

export const EXCLUDE_SOURCEMAPS = [
  // these packages have problems with their sourcemaps
  root('node_modules/@angular'),
  root('node_modules/rxjs'),
];

export const CUSTOM_COPY_FOLDERS = [

];

export const CUSTOM_PLUGINS_COMMON = [
  new LoaderOptionsPlugin({
    debug: true,
    options: {
      postcss: function () {
        return [
          Autoprefixer,
          CssNano,
        ];
      },
    },
  }),
  new ExtractTextWebpackPlugin('boot.css'),
];

export const CUSTOM_PLUGINS_DEV = [

];

export const CUSTOM_PLUGINS_PROD = [
  new ScriptExtHtmlWebpackPlugin({
    defaultAttribute: 'defer'
  }),
];

export const CUSTOM_RULES_COMMON = [
  {
    test: /boot.scss$/,
    use: ExtractTextWebpackPlugin.extract({
      loader: [
        'style-loader',
        'css-loader',
        'postcss-loader',
        'sass-loader'
      ],
    })
  },
  {
    test: /\.scss$/,
    use: [
      'to-string-loader',
      'css-loader',
      'postcss-loader',
      'sass-loader',
    ],
  },
];

export const CUSTOM_RULES_DEV = [

];

export const CUSTOM_RULES_PROD = [

];

export const CUSTOM_DEV_RULES = [

];

export const CUSTOM_PROD_RULES = [

];

export const CUSTOM_DEV_SERVER_OPTIONS = {
  watchOptions: {
    aggregateTimeout: 300,
    poll: 1000,
  },
};

export const CUSTOM_DEV_PLUGINS = [

];

export const HTML5_BASE_URL = '/';```

**Comment by fxck** [comment]
I was able to compile it with sass, just not with that `includePaths` option, it's crashing on

```
ERROR in ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
Module not found: Error: Can't resolve '/Users/fxck/www/ngtools-test/$$_gendir' in '/Users/fxck/www/ngtools-test/node_modules/@angular/core/src/linker'
 @ ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js 69:15-36 85:15-102
 @ ./~/@angular/core/src/linker.js
 @ ./~/@angular/core/src/core.js
 @ ./~/@angular/core/index.js
 @ multi vendors
```

which I frankly have no idea what means or how to debug it, but it's definitely related to those `includePaths`.

**Comment by katallaxie** [comment]
@fxck 🤔 there are some issues, I have worked on the AoT again https://github.com/katallaxie/angular2-preboot/tree/develop. There seems to be some issues remaining. Perhaps I should also let go `@ngtools/webpack`.

**Comment by fxck** [comment]
that would be a shame.. I managed to get https://github.com/katallaxie/angular2-preboot/issues/47#issuecomment-271354518 working by downgrading webpack and dev server, adding `root()` to `mainPath` and it seemed to compile just fine.. so basically the only problem I know about is this https://github.com/katallaxie/angular2-preboot/issues/48#issuecomment-271352614

**Comment by katallaxie** [comment]
@fxck 🤔 its emitting fine, but I have this `ERROR in ./aot/src/app/+detail/detail.component.ngfactory.ts
(90,29): error TS2305: Module ''*'' has no exported member 'Wrapper_RouterOutlet'.` which I seem not to fix.

**Comment by fxck** [comment]
https://github.com/angular/angular-cli/pull/2747 look like there's an open PR for `includePaths` support

**Comment by katallaxie** [comment]
@fxck have updated many things, solved many issues. hope that helps.

**Comment by fxck** [comment]
I'll give it a try. According to cli guys it, the plugin shouldn't really have problems with include paths, only cli, and there's PR for that.

**Comment by fxck** [comment]
@katallaxie cool, sass with `includePaths` seems to be working. You've done a really amazing job with this starter. 👍
