### ISSUE TITLE
some thoughts..

### ISSUE THREAD

**Issue by fxck** [katallaxie/angular2-preboot#56]
@katallaxie 

1. I think `config/helpers.ts` and `config/html-elements-plugin` should be moved from the `config` folder to say `utils` folder.. the latter perhaps to a npm package, neither really belong under config category
2. what was the reasoning behing `config/webpack.ts`? the way I see it this still belongs under `webpack.config.ts`, if the reason was the ability to override settings of these loaders, you could still do it with `CUSTOM_RULES_COMMON`, just check whether it contains one of the predefined loaders and replace it in that case
3. `config/head.ts` and `config/meta.ts` could be consolidated into one file
4. with 2. removed, `config/custom.ts` should probably be renamed to `webpack.ts`, as it's really a webpack config extension, also I'd drop the `CUSTOM_` prefix, it's not really users' concert, I'd also consider this
```typescript 
export const PLUGINS = {
  common: [ ],
  dev: [ ],
  prod: [ ]
};
```
instead of 
```typescript
export const CUSTOM_PLUGINS_COMMON = [

];

export const CUSTOM_PLUGINS_DEV = [

];

export const CUSTOM_PLUGINS_PROD = [

];
```
feels more readable, and since this config is typesafe anyway..

5. I don't know how often `spec.js` changes, but couldn't it perhaps be part of `karma.conf.js`? generally I'm not sure how I feel about these testing configs in the root folder, they are pretty specific and not really configurable the same way webpack.config is
6. to date, I still don't really understand https://github.com/katallaxie/angular2-preboot/blob/master/src/app/app.service.ts + https://github.com/katallaxie/angular2-preboot/blob/master/src/app/app.module.ts#L59 is that some sort of helper for HMR, or something actually usable in production?
7. what is this needed for https://github.com/katallaxie/angular2-preboot/blob/d28e1549e87c6a7fc26e306ee6b77faa42df0393/webpack.config.ts#L97-L98 I don't see hammerjs used anywhere
8. why is there `src/meta` with `humans.txt` and `robots.txt` and `src/assets` with the same files again? I'd leave them in assets

also out of curiosity, why are two tsconfigs and two main.browser needed, are those hacks to get it working, do you have link to any related issues?

**Comment by katallaxie** [comment]
@fxck thx, I will work through it :)

**Comment by fxck** [comment]
Just let me know which make sense to you and I can send some PRs.

**Comment by katallaxie** [comment]
@fxck I have moved the plugin to an npm package, and have removed the duplicate meta, and updated webpack a bit.
