### ISSUE TITLE
consider a new home for dll.ts / separating boilerplate from the actual app

### ISSUE THREAD

**Issue by fxck** [katallaxie/angular2-preboot#60]
First of all, it might be worth to look into https://github.com/AngularClass/angular2-webpack-starter/pull/1358 and see if it could be integrated here

The other thing is.. I think it would be nice to create a separation between files that are essentially part of **your app** and files that are simply there to get the framework and compilation running.

Basically I'd would be nice to have structure like this(pseudo naming):

```
- /src
--- index.html
--- /app
--- /assets
--- /meta
--- /_DO_NOT_TOUCH_
----- bootstrap.ts
----- bootstrap.aot.ts
----- browser.aot.ts
----- browser.ts
----- env.ts
```

..where `_DO_NOT_TOUCH_`(could probably be called `_bootstrap`) would include all the stuff that you rarely have to ever touch when you want to just get started, but is actually required by the framework or compilers, all these files should be easily upgradable from this repo without breaking your app or having merge conflicts.

But that leaves `dll.ts`, which you usually change somewhat often(in other words, is pretty specific to each project), I think we could throw it under `/config` folder, either in a separate file or under webpack-options.ts/old custom.ts, it should aldo be written in a more dumb way(a simple object / arrays), no functions, conditions.

Thoughts @katallaxie ?

// edit: most of the contents of `typings.d.ts` should probably be moved somewhere as well, as none of those declarations and interfaces is needed in the actual app, while I agree this file should still exist, it should be only for *user* defined custom type definitions

**Comment by katallaxie** [comment]
@fxck again, have been a bit 🍒 picking; have removed some legacy things. Have moved `dll.ts` to config. I would keep some things in place.
