### ISSUE TITLE
typescript not picking up on operators/observables added with dlls

### ISSUE THREAD

**Issue by fxck** [katallaxie/angular2-preboot#64]
After adding, for example, `'rxjs/add/observable/combineLatest'` and running `npm run dll`, and adding this for a test to app.component's `ngOnInit`

```typescript
    const a = new BehaviorSubject('a');
    const b = new BehaviorSubject('a');

    Observable
      .combineLatest(a,b)
      .subscribe((res) => console.log(res));
```

it's gonna throw

> Property 'combineLatest' does not exist on type 'typeof Observable'.

but it's gonna work properly..

@katallaxie

**Comment by fxck** [comment]
thought like it could be missing reference plugin here https://github.com/katallaxie/angular2-preboot/blob/master/config/defaults.ts#L127 but even after adding rxjs there, it still doesn't work.. so don't know

**Comment by katallaxie** [comment]
this works for me as expected. could you try?!

```/*
 * Angular 2 decorators and services
 */
import { ViewEncapsulation } from '@angular/core';
import { OnInit } from '@angular/core';
import { Component } from '@angular/core';
import { BehaviorSubject } from 'rxjs';
import { Observable } from 'rxjs';

import 'rxjs/add/observable/combineLatest';

/*
 * App Component
 * Top Level Component
 */
@Component({
  selector: 'my-app',
  encapsulation: ViewEncapsulation.None,
  styleUrls: ['./app.component.css'],
  templateUrl: './app.component.html'
})
export class AppComponent implements OnInit {

  public name = 'Angular 2 Preboot';
  public logo = '/img/angular.png';

  public ngOnInit() {
    console.log(`Initializing 'AppComponent'`);

    const a = new BehaviorSubject('a');
    const b = new BehaviorSubject('a');

    Observable
      .combineLatest(a,b)
      .subscribe((res) => console.log(res));

  }

}
```

**Comment by fxck** [comment]
Just checked what qdouble is doing:

https://github.com/qdouble/angular-webpack2-starter/blob/master/webpack.config.ts#L96 adding the whole `'rxjs'` to vendor dlls and then importing single operator patchers in main.browser.ts https://github.com/qdouble/angular-webpack2-starter/blob/master/src/main.browser.ts#L2

I'm not sure if whatever you put inside dlls is then actually used somehow in the production build, but I assume it is so? And if yes, it's not a good idea, since I'm pretty sure rxjs is not treeshakeable.. but if dlls have nothing to do with the final prod build, then perhaps this repo could do the same(assuming that webpack doesn't actually compile it along main file, because it knows it's part of dlls).

**Comment by katallaxie** [comment]
@fxck yep an `import` of the `rxjs` extensions is as such not tree-shackable, but it should be removed in minification as dead code. https://github.com/katallaxie/angular2-preboot/pull/65/commits/8e29ff0aacf1ddf04f46e653345a1663adbf6af6 should send all rxjs things to the `rxjs` bundle.

**Comment by fxck** [comment]
I think it would be worth doing a simple size comparison..

**Comment by katallaxie** [comment]
@fxck the size is the same.
