### ISSUE TITLE
is tree-shaking / dead code elimination truly working?

### ISSUE THREAD

**Issue by fxck** [katallaxie/angular2-preboot#75]
So I did a little test(https://github.com/fxck/angular2-preboot/tree/treeshaking-test) 

- included https://github.com/Promact/md2
- used only datepicker component
- did build:prod
- checked generated vendor.<hash>.bundle.js -> all of md2 libs included(search for `data-table` for example)

now this could be a problem with md2.. but checking their source code I don't see anything special that would make it non treeshakeable..

@katallaxie ?

**Comment by fxck** [comment]
tested with the official material2 as well, same problem, it's including the whole lib

**Comment by katallaxie** [comment]
could you share your code?! I see in the `module` of md2, that they call all imported modules.

**Comment by fxck** [comment]
did, it's on that branch I linked https://github.com/fxck/angular2-preboot/tree/treeshaking-test

**Comment by fxck** [comment]
I can add official material2 to that as well it you want, they should 100% be treeshake-ready

**Comment by katallaxie** [comment]
I will have a look at it...
